import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  ControllerSidebar: [{ type: "autogenerated", dirName: "download" }],
  tuningSidebar: [{ type: "autogenerated", dirName: "Tuning" }],
  manufactSidebar: [{ type: "autogenerated", dirName: "Manufacturers" }],
  developSidebar: [{ type: "autogenerated", dirName: "Contributing" }],
  // Autogenerated from the docs/ filesystem (frontmatter `sidebar_position` +
  // `_category_.json` files control ordering/labels). Only the index doc plus
  // the controllers/examples/setup/configurator subtrees are kept - see the
  // `sidebarItemsGenerator` in docusaurus.config.ts, which also flattens
  // configurator/tabs/* directly into the Configurator category.
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
