authors:
  rotorflight:
    name: Rotorflight
    description: Rotorflight Team
    url: https://github.com/rotorflight
    avatar: https://github.com/rotorflight.png

  pkaig:
    name: Phil Kaighin
    description: Maintainer
    url: https://github.com/pkaig
    avatar: https://github.com/pkaig.png
