name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: output
        id: output
        run: |
          echo "URL=https://${{ github.repository_owner }}.github.io" >> $GITHUB_OUTPUT
          echo "BASE_PATH=/" >> $GITHUB_OUTPUT

      - name: prepare env
        run: |
          touch .env
          echo URL=${{ steps.output.outputs.URL }} > .env
          echo BASE_PATH=${{ steps.output.outputs.BASE_PATH }} >> .env
          echo ORG=${{ github.repository_owner }} >> .env

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
